<?php

namespace Drupal\Tests\dkan;

use Composer\Autoload\ClassLoader;
use Drupal\common\Util\DrupalFiles;
use Drupal\Core\DrupalKernel;
use Drupal\metastore\Reference\Dereferencer;
use Drupal\node\Entity\Node;
use Drupal\Tests\common\Traits\ServiceCheckTrait;
use Drupal\Tests\UnitTestCase;
use FileFetcher\FileFetcher;
use MockChain\Chain;
use Symfony\Component\HttpFoundation\Request;

class DatasetTest extends UnitTestCase {
  use ServiceCheckTrait;

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    $appRoot = __DIR__ . '/../../../../..';
    $classLoader = new ClassLoader();
    $kernel = new DrupalKernel('prod', $classLoader, TRUE, $appRoot);
    $kernel->handle(new Request());

    $drupalFiles = (new Chain($this))
      ->add(DrupalFiles::class, 'getPublicFilesDirectory', $appRoot . "/sites/default/files")
      ->addd('getFileSystem', \Drupal::getContainer()->get('file_system'))
      ->getMock();

    \Drupal::getContainer()->set('dkan.common.drupal_files', $drupalFiles);
  }


  public function test() {
    $downloadUrl = "https://dkan-default-content-files.s3.amazonaws.com/district_centerpoints_small.csv";
    $dataset = '
    {
      "title": "Test #1",
      "description": "Yep",
      "identifier": "123",
      "accessLevel": "public",
      "modified": "06-04-2020",
      "keyword": ["hello"],
        "distribution": [
          {
            "title": "blah",
            "downloadURL": "' . $downloadUrl . '",
            "mediaType": "text/csv"
          }
        ]
    }';

    /* @var $service \Drupal\metastore\Service */
    $service = \Drupal::service('dkan.metastore.service');

    $identifier = $service->post('dataset', $dataset);
    $this->assertEquals("123", $identifier);

    drupal_static('metastore_dereference_method', Dereferencer::DEREFERENCE_OUTPUT_REFERENCE_IDS);

    $datasetWithReferencesJson = $service->get('dataset', '123');
    $datasetWithReferences = json_decode($datasetWithReferencesJson);
    $this->assertEquals(
      $downloadUrl,
      $datasetWithReferences->distribution[0]->data->downloadURL->data->filePath
    );

    /* @var $queueFactory \Drupal\Core\Queue\QueueFactory */
    $queueFactory = \Drupal::service('queue');
    $queue = $queueFactory->get('datastore_import');

    /* @var $queueWorkerManager \Drupal\Core\Queue\QueueWorkerManager */
    $queueWorkerManager = \Drupal::service('plugin.manager.queue_worker');
    $queueWorker = $queueWorkerManager->createInstance('datastore_import');
    while($item = $queue->claimItem()) {
      $queueWorker->processItem($item);
    }
  }

  private function removeAllNodes() {
    $nodes = Node::loadMultiple();
    foreach ($nodes as $node) {
      $node->delete();
    }
  }

  private function removeAllMappedFiles() {
    /* @var $filemappertable \Drupal\metastore\Storage\FileMapperDatabaseTable */
    $filemappertable = \Drupal::service('dkan.metastore.file_mapper_database_table');
    foreach ($filemappertable->retrieveAll() as $id) {
      $filemappertable->remove($id);
    }
  }

  private function removeAllFileFetchingJobs() {
    /* @var $jobStoreFactory \Drupal\common\Storage\JobStoreFactory */
    $jobStoreFactory = \Drupal::service('dkan.common.job_store');

    /* @var $jobStore \Drupal\common\Storage\JobStore */
    $jobStore = $jobStoreFactory->getInstance(FileFetcher::class);
    foreach ($jobStore->retrieveAll() as $id) {
      $jobStore->remove($id);
    }
  }

  private function flushQueues() {
    $dkanQueues = ['orphan_reference_processor', 'datastore_import'];
    foreach ($dkanQueues as $queueName) {
      /* @var $queueFactory \Drupal\Core\Queue\QueueFactory */
      $queueFactory = \Drupal::service('queue');
      $queue = $queueFactory->get($queueName);
      $queue->deleteQueue();
    }
  }

  private function removeFiles() {

    $dirs = ['dkan-tmp', 'distribution', 'resources'];
    foreach ($dirs as $dir) {
      $path = $this->getRelativeDruaplPath() . "/sites/default/files/{$dir}";
      if (file_exists($path)) {
        `rm -rf {$path}`;
      }
    }
  }

  public function tearDown() {
    parent::tearDown(); // TODO: Change the autogenerated stub
    $this->removeAllNodes();
    $this->removeAllMappedFiles();
    $this->removeAllFileFetchingJobs();
    $this->flushQueues();
    $this->removeFiles();
  }

}
